version: "3.7"

services:
  web:
    image: 2hog/docker-training-samples-micro-flask
    init: true
    deploy:
      replicas: 1
    environment:
      FLASK_ENV: ${ENVIRONMENT:-production}
      FLASK_DEBUG: ${DEBUG:-0}
    secrets:
      - auth_user
      - auth_password

secrets:
  auth_user:
    external: true
    name: micro-flask-auth-user

  auth_password:
    external: true
    name: micro-flask-auth-password
