version: "3.7"

services:
  web:
    image: 2hog/docker-training-samples-micro-flask
    init: true
    deploy:
      replicas: 1
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DEBUG: ${DEBUG:-false}
    secrets:
      - auth_user
      - auth_passwords

secrets:
  auth_user:
    external: true
    name: micro-flask-auth-user

  auth_password:
    external: true
    name: micro-flask-auth-user
