version: "3.7"

services:
  web:
    build:
      context: .
      args:
        pipenv_mode: dev
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-development}
      FLASK_DEBUG: ${DEBUG:-1}
      AUTH_USER: ${AUTH_USER:-antonis}
      AUTH_PASSWORD: ${AUTH_PASSWORD:-kalipetis}
    volumes:
      - .:/usr/src/app
    ports:
      - ${FLASK_MICRO_EXTERNAL_PORT:-5000}:5000
