apiVersion: v1
kind: Service
metadata:
  name: docker-training-samples-micro-flask
spec:
  type: NodePort
  selector:
    app: docker-training-samples-micro-flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
